mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='result'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('new-question/',views.new_question, name='new_question'),
    path('add_question',views.add_question,name="add_question"),
    path('tagged/<int:tag_id>',views.questions_of_tag,name="tagged"),

]

polls/models.py
from django.db import models
from django.utils import timezone
import datetime

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published', default=timezone.now)

    def __str__(self):
        return self.question_text
    
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text


class Tag(models.Model):
    name = models.CharField(max_length=200)
    questions = models.ManyToManyField(Question,related_name = 'tags')

polls/views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.db.models import F
from django.utils import timezone

from .models import Question, Choice, Tag

# Create your views here.
class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        return Question.objects.prefetch_related('tags').filter(
            pub_date__lte=timezone.now()
            ).order_by('-pub_date')[:5]

class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

    def get_queryset(self):
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
            })
    else:
       selected_choice.votes = F('votes')+ 1
       selected_choice.save() 
    return HttpResponseRedirect(reverse('polls:result',args=(question_id,)))

# class AddQuestionView(generic.DetailView):
#     model = Question
#     template_name = 'polls/detail.html' 

def new_question(request):
    return render(request, 'polls/new-question.html')

def add_question(request):
    tags = [request.POST[key] for key in request.POST.keys() if key.startswith("tag")]
    # print(tags)
    # tag = request.POST["tag1"]
    question = request.POST["question"]
    choice1 = request.POST["choice1"]
    choice2 = request.POST['choice2']

    question = Question(question_text=question)
    question.save()
    Choice.objects.create(question=question, choice_text=choice1)
    Choice.objects.create(question=question, choice_text=choice2)
    for tag in tags:
        question.tags.create(name=tag)
    return HttpResponseRedirect(reverse('polls:index'))

    # print("****************************************")
    # print(tag,question,choice1,choice2)
    # print("****************************************")

def questions_of_tag(request, tag_id):
    return render(request,'polls/questions_of_tag.html', {'tag':Tag.objects.prefetch_related('questions').get(pk=tag_id)})

polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
<form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
    {% endfor %}
<input type="submit" value="Vote">
</form>

polls/templates/polls/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
<h1>Home</h1><br>
<a href="new-question/" >post a poll</a>
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
    <hr>
        <small>tags:
            {% for tag in question.tags.all %}
            <a href="{% url 'polls:tagged' tag.id %}">{{tag.name}}</a>, 
            {% endfor %}
        </small>
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

polls/templates/polls/new-question.html
{% load static %}
<h1>Add a question</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
<form action="/polls/add_question" method="post">
    {% csrf_token %}
        <div id="tag">
            <label for="tag1">Tag</label><br>
            <input type="text" name="tag1" id="tag1" class="tag" > <br>
        </div>
        <button onclick=addTag() type="button">Add Tag</button><br>
        <label for="question">Question</label><br>
        <input type="text" name="question" id="question" > 
        <div id="choices">
            <label for="choice1">Choice 1</label><br>
            <input type="text" id="choice1" name=choice1><br>
            <label for="choice2">Choice 2</label><br>
            <input type="text" id="choice2" name=choice2> 
        </div>

<input type="submit" value="Submit">
</form>
<script src="{% static 'polls/script.js' %}"></script>

polls/templates/polls/questions_of_tag.html
{% for question in tag.questions.all %}
    <li><a href="{% url 'polls:detail' question.id %}">{{ question }}</a></li>
{% endfor %}

polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>